-- MySQL Script generated by MySQL Workbench
-- Sat Dec 26 16:33:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Linije`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Linije` (
  `idLinije` INT NOT NULL AUTO_INCREMENT,
  `Naziv_Linije` VARCHAR(100) NOT NULL,
  `Polazna_Stanica` VARCHAR(45) NOT NULL,
  `Dolazna_Stanica` VARCHAR(45) NOT NULL,
  `Vrijeme_Polaska` TIME NOT NULL,
  `Vrijeme_Dolaska` TIME NOT NULL,
  `Sifra_Prevoznika` INT NOT NULL,
  `Naziv_Prevoznika` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLinije`),
  UNIQUE INDEX `idLinije_UNIQUE` (`idLinije` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relacije`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relacije` (
  `idRelacije` INT NOT NULL AUTO_INCREMENT,
  `idLinije` INT NOT NULL,
  `Destinacija` VARCHAR(45) NOT NULL,
  `Vrijeme_Dolaska` TIME NOT NULL,
  `Cijena_Prevoza` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idRelacije`),
  UNIQUE INDEX `idRelacije_UNIQUE` (`idRelacije` ASC) VISIBLE,
  INDEX `idLinije_idx` (`idLinije` ASC) VISIBLE,
  CONSTRAINT `idLinije`
    FOREIGN KEY (`idLinije`)
    REFERENCES `mydb`.`Linije` (`idLinije`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prevoznici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prevoznici` (
  `idPrevoznici` INT NOT NULL AUTO_INCREMENT,
  `Naziv_Prevoznika` VARCHAR(45) NOT NULL,
  `Mjesto` VARCHAR(45) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPrevoznici`),
  UNIQUE INDEX `idPrevoznici_UNIQUE` (`idPrevoznici` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uposlenici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uposlenici` (
  `idUposlenici` INT NOT NULL AUTO_INCREMENT,
  `Ime_uposlenog` VARCHAR(50) NOT NULL,
  `Prezime_uposlenog` VARCHAR(50) NOT NULL,
  `Broj_Biletare` INT NOT NULL,
  UNIQUE INDEX `idUposlenici` () VISIBLE,
  PRIMARY KEY (`idUposlenici`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prodaja_Karata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prodaja_Karata` (
  `idProdaja_Karata` INT NOT NULL AUTO_INCREMENT,
  `Datum_Izdavanja` DATE NOT NULL,
  `Vrijeme_Izdavanja` TIME NOT NULL,
  `Datum_Putovanja` DATE NOT NULL,
  `Vrijeme_Putovanja` TIME NOT NULL,
  `idLinije` INT NOT NULL,
  `Opis_Linija` VARCHAR(100) NOT NULL,
  `idPrevoznika` INT NOT NULL,
  `Naziv_Prevoznika` VARCHAR(45) NOT NULL,
  `idRelacije` INT NOT NULL,
  `Naziv_Destinacije` VARCHAR(100) NOT NULL,
  `Cijena_Karte` DECIMAL(10,2) NOT NULL,
  `Kolodvorska_Usluga` DECIMAL(10,2) NOT NULL,
  `Uposlenik` INT NOT NULL,
  PRIMARY KEY (`idProdaja_Karata`),
  UNIQUE INDEX `idProdaja_Karata_UNIQUE` (`idProdaja_Karata` ASC) VISIBLE,
  INDEX `idLinije_idx` (`idLinije` ASC) VISIBLE,
  INDEX `idPrevoznika_idx` (`idPrevoznika` ASC) VISIBLE,
  INDEX `idRelacije` (`idRelacije` ASC) VISIBLE,
  INDEX `idUposlenici_idx` (`Uposlenik` ASC) VISIBLE,
  CONSTRAINT `idLinije`
    FOREIGN KEY (`idLinije`)
    REFERENCES `mydb`.`Linije` (`idLinije`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idPrevoznika`
    FOREIGN KEY (`idPrevoznika`)
    REFERENCES `mydb`.`Prevoznici` (`idPrevoznici`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idRelacije`
    FOREIGN KEY (`idRelacije`)
    REFERENCES `mydb`.`Relacije` (`idRelacije`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idUposlenici`
    FOREIGN KEY (`Uposlenik`)
    REFERENCES `mydb`.`Uposlenici` (`idUposlenici`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`Pregled prevoznika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pregled prevoznika` (`Adresa` INT);

-- -----------------------------------------------------
-- View `mydb`.`Pregled prevoznika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pregled prevoznika`;
USE `mydb`;
CREATE  OR REPLACE VIEW `Pregled prevoznika` AS
Select Adresa
From Prevoznici;
where Naziv_Prevoznika = "Unatransport";

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
