-- MySQL Script generated by MySQL Workbench
-- Sat Dec 26 16:38:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Linije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linije` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Linije` (
  `idLinije` INT NOT NULL AUTO_INCREMENT,
  `Naziv_Linije` VARCHAR(100) NOT NULL,
  `Polazna_Stanica` VARCHAR(45) NOT NULL,
  `Dolazna_Stanica` VARCHAR(45) NOT NULL,
  `Vrijeme_Polaska` TIME NOT NULL,
  `Vrijeme_Dolaska` TIME NOT NULL,
  `Sifra_Prevoznika` INT NOT NULL,
  `Naziv_Prevoznika` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLinije`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idLinije_UNIQUE` ON `Linije` (`idLinije` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Prevoznici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prevoznici` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Prevoznici` (
  `idPrevoznici` INT NOT NULL AUTO_INCREMENT,
  `Naziv_Prevoznika` VARCHAR(45) NOT NULL,
  `Mjesto` VARCHAR(45) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPrevoznici`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPrevoznici_UNIQUE` ON `Prevoznici` (`idPrevoznici` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Prodaja_Karata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prodaja_Karata` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Prodaja_Karata` (
  `idProdaja_Karata` INT NOT NULL AUTO_INCREMENT,
  `Datum_Izdavanja` DATE NOT NULL,
  `Vrijeme_Izdavanja` TIME NOT NULL,
  `Datum_Putovanja` DATE NOT NULL,
  `Vrijeme_Putovanja` TIME NOT NULL,
  `idLinije` INT NOT NULL,
  `Opis_Linija` VARCHAR(100) NOT NULL,
  `idPrevoznika` INT NOT NULL,
  `Naziv_Prevoznika` VARCHAR(45) NOT NULL,
  `idRelacije` INT NOT NULL,
  `Naziv_Destinacije` VARCHAR(100) NOT NULL,
  `Cijena_Karte` DECIMAL(10,2) NOT NULL,
  `Kolodvorska_Usluga` DECIMAL(10,2) NOT NULL,
  `Uposlenik` INT NOT NULL,
  PRIMARY KEY (`idProdaja_Karata`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idProdaja_Karata_UNIQUE` ON `Prodaja_Karata` (`idProdaja_Karata` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idRelacije` ON `Prodaja_Karata` (`idRelacije` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Relacije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Relacije` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Relacije` (
  `idRelacije` INT NOT NULL AUTO_INCREMENT,
  `idLinije` INT NOT NULL,
  `Destinacija` VARCHAR(45) NOT NULL,
  `Vrijeme_Dolaska` TIME NOT NULL,
  `Cijena_Prevoza` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idRelacije`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idRelacije_UNIQUE` ON `Relacije` (`idRelacije` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Uposlenici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Uposlenici` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Uposlenici` (
  `idUposlenici` INT NOT NULL AUTO_INCREMENT,
  `Ime_uposlenog` VARCHAR(50) NOT NULL,
  `Prezime_uposlenog` VARCHAR(50) NOT NULL,
  `Broj_Biletare` INT NOT NULL,
  PRIMARY KEY (`idUposlenici`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idUposlenici` ON `Uposlenici` () VISIBLE;

SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- View `Pregled prevoznika`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `Pregled prevoznika` ;
SHOW WARNINGS;
USE `mydb`;
CREATE  OR REPLACE VIEW `Pregled prevoznika` AS
Select Adresa
From Prevoznici;
where Naziv_Prevoznika = "Unatransport";
SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `Linije`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `Linije` (`idLinije`, `Naziv_Linije`, `Polazna_Stanica`, `Dolazna_Stanica`, `Vrijeme_Polaska`, `Vrijeme_Dolaska`, `Sifra_Prevoznika`, `Naziv_Prevoznika`) VALUES (1, 'Bihac-Sarajevo-Bihac', 'Bihac', 'Sarajevo', '13:00', '21:00', 1, 'Centrotrans Bus');
INSERT INTO `Linije` (`idLinije`, `Naziv_Linije`, `Polazna_Stanica`, `Dolazna_Stanica`, `Vrijeme_Polaska`, `Vrijeme_Dolaska`, `Sifra_Prevoznika`, `Naziv_Prevoznika`) VALUES (2, 'Bihac-Banja Luka-Bihac', 'Bihac', 'Banja Luka', '11:15', '15:20', 2, 'Unatransport ');
INSERT INTO `Linije` (`idLinije`, `Naziv_Linije`, `Polazna_Stanica`, `Dolazna_Stanica`, `Vrijeme_Polaska`, `Vrijeme_Dolaska`, `Sifra_Prevoznika`, `Naziv_Prevoznika`) VALUES (3, 'Bihac-Tuzla-Bihac', 'Bihac', 'Tuzla', '09:00', '16:00', 2, 'Unatransport');
INSERT INTO `Linije` (`idLinije`, `Naziv_Linije`, `Polazna_Stanica`, `Dolazna_Stanica`, `Vrijeme_Polaska`, `Vrijeme_Dolaska`, `Sifra_Prevoznika`, `Naziv_Prevoznika`) VALUES (4, 'Bihac-Ljubljana-Bihac', 'Bihac', 'Ljubljana', '08:30', '14:30', 3, 'FlixBus');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Prevoznici`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `Prevoznici` (`idPrevoznici`, `Naziv_Prevoznika`, `Mjesto`, `Adresa`) VALUES (1, 'Centrotrans', 'Sarajevo', 'Titova Ulica 14');
INSERT INTO `Prevoznici` (`idPrevoznici`, `Naziv_Prevoznika`, `Mjesto`, `Adresa`) VALUES (2, 'Unatransport', 'Bihac', 'I.Ljubijankica 12');
INSERT INTO `Prevoznici` (`idPrevoznici`, `Naziv_Prevoznika`, `Mjesto`, `Adresa`) VALUES (3, 'FlixBus', 'Bihac', 'R.Lopasica 22');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Prodaja_Karata`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `Prodaja_Karata` (`idProdaja_Karata`, `Datum_Izdavanja`, `Vrijeme_Izdavanja`, `Datum_Putovanja`, `Vrijeme_Putovanja`, `idLinije`, `Opis_Linija`, `idPrevoznika`, `Naziv_Prevoznika`, `idRelacije`, `Naziv_Destinacije`, `Cijena_Karte`, `Kolodvorska_Usluga`, `Uposlenik`) VALUES (1, '17.05.2020', '14:38', '20.05.2020', '13:00', 1, 'Bihac-Sarajevo-Bihac', 1, 'Centrotrans', 4, 'Sarajevo', 45,00, 1,00, DEFAULT);
INSERT INTO `Prodaja_Karata` (`idProdaja_Karata`, `Datum_Izdavanja`, `Vrijeme_Izdavanja`, `Datum_Putovanja`, `Vrijeme_Putovanja`, `idLinije`, `Opis_Linija`, `idPrevoznika`, `Naziv_Prevoznika`, `idRelacije`, `Naziv_Destinacije`, `Cijena_Karte`, `Kolodvorska_Usluga`, `Uposlenik`) VALUES (2, '05.06.2020', '09:21', '06.06.2020', '08:30', 2, 'Bihac-Banja Luka-Bihac', 2, 'Unatransport', 3, 'Banja Luka', 26,00, 1,00, DEFAULT);
INSERT INTO `Prodaja_Karata` (`idProdaja_Karata`, `Datum_Izdavanja`, `Vrijeme_Izdavanja`, `Datum_Putovanja`, `Vrijeme_Putovanja`, `idLinije`, `Opis_Linija`, `idPrevoznika`, `Naziv_Prevoznika`, `idRelacije`, `Naziv_Destinacije`, `Cijena_Karte`, `Kolodvorska_Usluga`, `Uposlenik`) VALUES (3, '28.06.2020', '10:49', '30.06.2020', '09:45', 3, 'Bihac-Tuzla-Bihac', 2, 'Unatransport', 4, 'Tuzla', 55,00, 1,00, DEFAULT);
INSERT INTO `Prodaja_Karata` (`idProdaja_Karata`, `Datum_Izdavanja`, `Vrijeme_Izdavanja`, `Datum_Putovanja`, `Vrijeme_Putovanja`, `idLinije`, `Opis_Linija`, `idPrevoznika`, `Naziv_Prevoznika`, `idRelacije`, `Naziv_Destinacije`, `Cijena_Karte`, `Kolodvorska_Usluga`, `Uposlenik`) VALUES (4, '03.07.2020', '17:04', '04.07.2020', '09:30', 4, 'Bihac-Ljubljana-Bihac', 3, 'Flixbus', 2, 'Ljubljana', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `Prodaja_Karata` (`idProdaja_Karata`, `Datum_Izdavanja`, `Vrijeme_Izdavanja`, `Datum_Putovanja`, `Vrijeme_Putovanja`, `idLinije`, `Opis_Linija`, `idPrevoznika`, `Naziv_Prevoznika`, `idRelacije`, `Naziv_Destinacije`, `Cijena_Karte`, `Kolodvorska_Usluga`, `Uposlenik`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Relacije`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (1, 1, 'Kljuc', '14:00', 15,00);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (2, 1, 'Jajce', '16:15', 23,00);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (3, 1, 'Travnik', '18:45', 32,00);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (4, 1, 'Sarajevo', '20:00', 45,00);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (1, 2, 'Bos.Krupa', '09:00', 8,00);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (2, 2, 'Prijedor', '10:15', 16,00);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (3, 2, 'Banja Luka', '11:30', 26,00);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (1, 3, 'Prijedor', '11:00', 16,00);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (2, 3, 'Banja Luka', '12:25', 26,00);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (3, 3, 'Doboj', '14:10', 32,00);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (4, 3, 'Tuzla', '16:45', 55,50);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (1, 4, 'Karlovac', '10:30', 20,50);
INSERT INTO `Relacije` (`idRelacije`, `idLinije`, `Destinacija`, `Vrijeme_Dolaska`, `Cijena_Prevoza`) VALUES (2, 4, 'Ljubljana', '14:30', 63,00);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Uposlenici`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `Uposlenici` (`idUposlenici`, `Ime_uposlenog`, `Prezime_uposlenog`, `Broj_Biletare`) VALUES (1, 'Armin', 'Omanovic', 2);
INSERT INTO `Uposlenici` (`idUposlenici`, `Ime_uposlenog`, `Prezime_uposlenog`, `Broj_Biletare`) VALUES (2, 'Mirela', 'Tutic', 1);
INSERT INTO `Uposlenici` (`idUposlenici`, `Ime_uposlenog`, `Prezime_uposlenog`, `Broj_Biletare`) VALUES (3, 'Tarik', 'Busuladzic', 3);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
